# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'SnapShare' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SnapShare
  pod 'Alamofire'
  pod 'CropViewController'
  pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '2.x'
  pod 'JGProgressHUD'
end
